---
- name: Setup MySQL with accounts db & remote login
  hosts: dbsrvgrp
  gather_facts: no
  tasks:
   - name: Installing MySQL service& dependencies
     package:
       name: "{{item}}"
       state: present
       update_cache: yes
       cache_valis_time: 86400
     loop: 
       - mysql-server
       - mysql-client
       - python-mysqldb
       - python3-mysqldb
       - libmysqlclient-dev
     ignore_error: yes
     tags: 
       - package
     
   - name: Start & enable mysql service
     service:
       name: mysql
       state: started
       enabled: yes
     tags:
       - svc
   
   - name: creating mysql user
     mysql_user:
       name: "{{dbuser}}"
       password: "{{dbpass}}"
       priv: '*.*:ALL'
       host: '%'
       state: present
 
   - name: Creating accounts DB
     mysql_db:
       name: "{{dbname}}"
       state: present

   - name: Enable remote login to mysql svc
     lineinfile:
       path: /etc/mysql/mysql.conf.d/mysqld.conf
       regexp: '^bind-address'
       line: 'bind-address = 0.0.0.0/0'
       backup: yes
     notify:
       - Restart mysql
     tags:
       - conf

  handlers: 
  - name: Restart mysql
    service:
      name: mysql
      state: restarted  


















      
