---
- name: Deploy SQL file on accounts db
  hosts: dbsrvgrp
  gather_facts: no
  tasks:
   - name: Copy SQL to dbsrv
     copy:
       src: files/db_backup.yml
       dest: /tmp/db_backup.yml
     tags: 
       - deploy
   
   - name: Restoring DB
     mysql_db:
       name: accounts
       login_user: "{{dbuser}}"
       login_password: "{{dbpass}}"
       state: import
       target: /tmp/db_backup.sql
    notify: 
       - Restart mysql
    tags:
       - deploy
