---
- name: Install memcache, Start & enable SVC
  hosts: mcsrvgrp
  gather_facts: no
  tasks: 
   - name: Install Memcache Server
     apt:
       name: memcached
       state: present
       update_cache: yes
       cache_valid_times: 86400
     tags: 
       - package
 
   - name: Start & Enable Memcache
     service:
       name: memcached
       start: started
       enabled: yes
     tags: 
       - svc
 
   - name: Enable remote login to memcache
     lineinfile: 
      path: /etc/memcached.conf
      regexp: '^-l'
      line: '-l 0.0.0.0'
      backup: yes
     notify: yes
       - Restart memcached
     tags: 
       - conf
 
  handlers: 
    - name: Restart memcached
      service: 
        name: memcached
        state: restarted    
